In [13]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df = pd.read_csv('gurgaon_properties.csv')

In [14]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
546,12 Bedroom House for sale in Uppals Southend,house,uppal southend,6.75,31915.0,2115.0,Plot area 235(196.49 sq.m.),12.0,12.0,3+,Others,"Uppals Southend, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address......Uppal southend sector 49 availabl...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
680,3 BHK Flat in Sector 65 Gurgaon,flat,m3m golfestate,4.94,16233.0,3043.0,Super Built up area 3043(282.7 sq.m.),3.0,4.0,3,Servant Room,"Tower, Sector 65 Gurgaon, Gurgaon, Haryana",15.0,North-East,5 to 10 Year Old,"['Sector 54 Chowk Metro Station', 'Sahara Mall...","M3m golfestate in sector 65, gurgaon is a read...",[],"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2816,4 BHK Flat in Sector 81 Gurgaon,flat,bestech park view grand spa,3.00,9419.0,3185.0,Super Built up area 3185(295.9 sq.m.),4.0,5.0,2,Servant Room,"Sector-81, Sector 81 Gurgaon, Gurgaon, Haryana",6.0,South,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, IMT Manesar', 'Dwa...",Located in the popular residential address of ...,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
1980,3 BHK Flat in Garauli Kalan,flat,ashiyara 2,0.45,4500.0,1000.0,Super Built up area 1000(92.9 sq.m.),3.0,3.0,2,not available,"Garauli Kalan, Gurgaon, Haryana",18.0,NaN,Jan 2025,"['Shri Balaji Hospital and Trauma Center', 'Ka...",Residential apartment for sell.The property ha...,NaN,NaN,NaN
3573,2 BHK Flat in Sohna,flat,hcbs sports ville,0.27,4345.0,621.0,Built Up area: 619 (57.51 sq.m.),2.0,2.0,2,not available,"Sohna, Gurgaon, Haryana",10.0,NaN,1 to 5 Year Old,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...",Raw flat as given by builder. Good location ne...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management4 out of 5', 'Green Area4 out of 5..."

In [15]:
df.shape

(4010, 20)

In [16]:
df.duplicated().sum()

np.int64(2)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4010 entries, 0 to 4009
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    4010 non-null   object
 1   property_type    4010 non-null   object
 2   society          4009 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3981 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   float64
 8   bathroom         3961 non-null   float64
 9   balcony          3961 non-null   object
 10  additionalRoom   4010 non-null   object
 11  address          3991 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3795 non-null   object
 16  description      4002 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3546 non-null   object
dtypes: float64(6), object(14)
memory usage: 626.7+ KB

In [18]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                69
price_per_sqft       29
area                 69
areaWithType         49
bedRoom              49
bathroom             49
balcony              49
additionalRoom        0
address              19
floorNum             70
facing             1226
agePossession        50
nearbyLocations     215
description           8
furnishDetails     1081
features            758
rating              464
dtype: int64

In [19]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip().str.lower())

In [20]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Surat Nagar 1,flat,zara aavaas,surat nagar 1,0.20,6644.0,301.0,Carpet area: 301 (27.96 sq.m.),1.0,2.0,2,not available,"Surat Nagar 1, Gurgaon, Haryana",3.0,NaN,0 to 1 Year Old,"['Ardee Mall', 'Northern Peripheral Road', 'Mp...",We are the proud owners of this 1 bhk apartmen...,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,2 BHK Flat in Sector 103 Gurgaon,flat,landmark the residency,sector 103,0.90,6666.0,1350.0,Super Built up area 1350(125.42 sq.m.),2.0,2.0,2,not available,"Sector 103 Gurgaon, Gurgaon, Haryana",1.0,South-West,1 to 5 Year Old,"['State bank ATM', 'Dr. Hitesh Dawar', 'Bhardw...",We are the proud owners of this 2 bhk apartmen...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Intercom Facility',...","['Connectivity4 out of 5', 'Lifestyle4 out of ..."
2,3 BHK Flat in Dwarka Expressway Gurgaon,flat,ramprastha city,dwarka expressway,1.30,9027.0,1440.0,Super Built up area 1440(133.78 sq.m.),3.0,3.0,2,not available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",3.0,NaN,By 2023,"['Raheja Mall', 'HUDA Market, Sector 14', 'Gur...",We are the proud owners of this 3 bhk apartmen...,[],NaN,NaN
3,4 BHK Flat in Sector 60 Gurgaon,flat,ireo skyon,sector 60,3.80,13571.0,2800.0,Super Built up area 2800(260.13 sq.m.)Built Up...,4.0,5.0,3,Servant Room,"Block B, Sector 60 Gurgaon, Gurgaon, Haryana",15.0,East,5 to 10 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...",Ireo skyon all sizes available at best price g...,"['4 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction5 out of..."
4,1 BHK Flat in Sector 36 Gurgaon,flat,breez global heights,sector 36,0.24,5825.0,412.0,Carpet area: 412 (38.28 sq.m.),1.0,1.0,1,not available,"Sector 36 Gurgaon, Gurgaon, Haryana",8.0,NaN,0 to 1 Year Old,"['S.R.S. Hospital and Critical Care Unit', 'Sh...",Residential apartment for sell.The property ha...,"['1 Wardrobe', '2 Fan', '1 Exhaust Fan', '5 Li...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",NaN

In [21]:
df['sector'].value_counts()

sector
sohna                                                        164
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 109                                                   102
sector 69                                                     94
sector 65                                                     91
sector 81                                                     91
sector 90                                                     90
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 48                                                     63
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 70a                                                    54
sector 70                                                     54
nirvana country                                               53
sector 37c                                                    53
sector-33 sohna                                               52
sector 66                                                     52
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 103                                                    45
dlf phase 1                                                   43
dlf phase 2                                                   43
sector 113                                                    43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 72                                                     30
sector 68                                                     30
sector 77                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    25
sector 111                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
dlf phase 3                                                   22
sector 22                                                     21
sector 63a                                                    20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sector 99                                                     16
sushant lok phase 3                                           16
sector 60                                                     15
sector 52                                                     15
sector 14                                                     15
sector 63                                                     15
gwal pahari                                                   14
rajendra park                                                 14
dlf phase 5                                                   14
sector 53                                                     14
sector 1 imt manesar                                          14
sector 76                                                     14
sector 3                                                      14
laxman vihar phase 2                                          13
sector 36a                                                    13
sector 46                                                     13
sector 31                                                     12
sector 93                                                     12
uppals southend                                               12
sohna road                                                    12
sector 39                                                     12
sector 38                                                     12
sector 50                                                     12
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 47                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
south city 1                                                   9
sector 95a                                                     9
sector 55                                                      9
sector 4                                                       9
ashok vihar phase 2                                            9
palam vihar extension                                          9
sector 57                                                      8
c block sushant lok phase 1                                    8
malibu town                                                    8
mehrauli  road                                                 8
dwarka expressway                                              8
sector 59                                                      8
sector 40                                                      8
sector 10a                                                     8
sector 89 a                                                    8
sector 43                                                      8
new colony                                                     7
sector 51                                                      7
sector 58                                                      7
sector 26                                                      7
sector 5                                                       7
sector 36 sohna                                                7
sector 11                                                      7
rajiv nagar                                                    7
mianwali colony                                                7
surat nagar 1                                                  7
arjun nagar                                                    6
jyoti park                                                     6
sector 73                                                      6
jacobpura                                                      6
ashok vihar                                                    6
sector 1                                                       6
sector 23a                                                     5
manesar                                                        5
subhash nagar                                                  5
sector 30                                                      5
sushant lok phase 2                                            5
sector 80                                                      5
sector 9                                                       5
new palam vihar                                                5
sector 28                                                      5
surya vihar                                                    5
saraswati vihar                                                5
greenwood city                                                 5
sector 2                                                       5
sector 105                                                     5
ansal plaza                                                    5
dayanand colony                                                5
chakkarpur                                                     5
sector 23                                                      4
adarsh nagar                                                   4
shivaji nagar                                                  4
sector 12a                                                     4
sector 17                                                      4
ravi nagar                                                     4
krishna colony                                                 4
dharam colony                                                  4
sector 12                                                      4
sector 6                                                       4
devilal colony                                                 4
valley view estate                                             4
bhim nagar                                                     4
bhondsi                                                        4
garhi harsaru                                                  4
sector 45                                                      4
imt manesar                                                    4
madanpuri                                                      4
vishnu garden                                                  4
sector 3a                                                      4
new                                                            4
shivpuri                                                       4
suncity                                                        4
baldev nagar                                                   4
sector 36                                                      4
b block sushant lok phase 1                                    3
shakti nagar                                                   3
laxmi garden                                                   3
sector 88b                                                     3
a block sushant lok phase 1                                    3
gandhi nagar                                                   3
mg road                                                        3
sector 27                                                      3
prem nagar                                                     3
sector 15                                                      3
maruti kunj                                                    3
sector 110 a                                                   3
sector 17b                                                     3
patel nagar                                                    3
sector 17a                                                     3
sector 8                                                       3
new basti                                                      2
daulatabad                                                     2
bissar                                                         2
new palam vihar phase 2                                        2
surat nagar phase 2                                            2
mayfield garden                                                2
golf course road                                               2
sector 41                                                      2
, delhi ncr                                                    2
bhawani enclave                                                2
ambience island                                                2
west rajiv nagar                                               2
surat nagar                                                    2
shanti nagar                                                   2
sector 24                                                      2
block a surya vihar                                            2
hira nagar                                                     2
sector 15 part 1                                               2
rosewood                                                       2
golf course ext road                                           2
mohan nagar                                                    2
new palam vihar phase 1                                        2
sector-2 sohna                                                 2
sheetla colony                                                 2
sector 32                                                      2
shankar vihar                                                  2
sushant lok                                                    2
nars                                                           2
faridabad road                                                 2
iffco chowk                                                    2
manohar nagar                                                  2
lajpat nagar                                                   2
acharya puri                                                   2
rajiv chowk                                                    2
sohna  road                                                    2
farukhnagar                                                    2
sector 15 part 2                                               2
sispal vihar                                                   2
sector-11 sohna                                                2
sector 21                                                      2
pratap nagar                                                   2
samaspur                                                       2
south city                                                     1
ansal's palam vihar                                            1
near khandsa road                                              1
vir nagar                                                      1
godrej aria , sector 79 ,                                      1
urban estate, sector 5                                         1
civil l                                                        1
block h ashok vihar phase iii extension                        1
sadar bazar                                                    1
anand garden, sector-105                                       1
near sector 1 market                                           1
sector 13                                                      1
ashok vihar phase 3                                            1
part 3 sector 5                                                1
naharpur rupa                                                  1
saroop garden rajendra park                                    1
ravi nager basai road                                          1
huda saraswati vihar                                           1
near pataudi chowk                                             1
new jyoti park                                                 1
sai kunj                                                       1
heritage city                                                  1
rattan garden                                                  1
mahavir pura                                                   1
cyber city                                                     1
bptp                                                           1
mahalaxmi garden, rajendra place                               1
sector-7 hous                                                  1
near nand hospital                                             1
sector-5 sheetla colony                                        1
jacobpura near sadar bazar                                     1
b1 block sector 57                                             1
sector-35 sohna                                                1
gopal nagar, garhi ghasita, sonipat                            1
block g sector-57                                              1
sector 5 chowk                                                 1
sector 37a                                                     1
sector 37b                                                     1
ram nagar                                                      1
hsiidc plot sector 1 imt manesar                               1
khandsa                                                        1
v block dlf phase 3                                            1
sector 21a faridabad                                           1
rajiv colony                                                   1
kheri                                                          1
bhora kalan                                                    1
nirvana country pocket h                                       1
hno 13 sagar enclave sura                                      1
kanahi                                                         1
g block dlf city phase 1                                       1
jat colony,fazilpur/taj nagar road                             1
new colony, sector 7                                           1
near euro                                                      1
devi lal colony gali no 12 gurgaon nr omkar public school      1
alipur                                                         1
garauli kalan                                                  1
saraswati enclave                                              1
sector-5 sohna                                                 1
old delhi road, opp sector-14                                  1
sector 17c                                                     1
shivji park colony                                             1
sector 4 urban estate                                          1
ats marigold                                                   1
om nagar                                                       1
ashok vihar phase i                                            1
udyog vihar phase 1                                            1
lucknow                                                        1
sector 9b                                                      1
dhankot                                                        1
begampur khatola                                               1
sultanpur                                                      1
tekchand nagar                                                 1
bhimgarh kheri phase 3                                         1
park view                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
pataudi road                                                   1
sector 42                                                      1
carterpuri village                                             1
damdma                                                         1
laxmna vihar, phase 2                                          1
laxman vihar, railway road,                                    1
Name: count, dtype: int64

In [22]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [23]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [24]:
df['sector'].value_counts()

sector
sohna road                    164
sector 102                    113
sector 85                     110
sector 92                     104
sector 109                    102
sector 69                      94
sector 65                      91
sector 81                      91
sector 90                      90
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 48                      63
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 89                      56
sector 2                       55
sector 70a                     54
sector 70                      54
sector 43                      53
sector 37c                     53
sector-33 sohna road           52
sector 66                      52
sector 84                      51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 72                      30
sector 77                      29
sector 71                      27
sector 112                     25
sector 111                     24
sector 24                      24
sector 57                      24
sector 33                      23
sector 88a                     23
sector 14                      23
sector 105                     23
sector 67a                     22
sector 11                      21
sector 22                      21
sector 63a                     20
sector 82a                     20
sector 3                       20
sector 47                      19
sector 78                      19
gwal pahari                    18
sector 74                      18
sector 62                      17
sector 91                      17
sector 99                      16
sector 110                     16
sector 60                      15
sector 52                      15
sector 63                      15
sector 53                      14
sector 76                      14
sector 55                      14
sector 1 manesar               14
sector 6                       13
sector 36a                     13
sector 9                       13
sector 4 phase 2               13
sector 46                      13
sector 38                      12
sector 31                      12
sector 39                      12
sohna road road                12
sector 93                      12
sector 3 phase 3 extension     11
sector 9a                      11
sector 13                      11
sector 41                      11
sector 1a manesar              10
sector 95a                      9
manesar                         9
sector 3 phase 2                9
sector 23                       9
sector 8                        9
sector 2 extension              9
sector 45                       9
dwarka expressway               8
c block sector 43               8
sector 17                       8
sector 10a                      8
sector 59                       8
sector 89 a                     8
sector 40                       8
sector 51                       7
sector 21                       7
sector 5                        7
sector 36 sohna road            7
sector 58                       7
sector 1                        6
sector 73                       6
sector 80                       5
sector 23a                      5
new sector 2                    5
sector 30                       5
sector 36                       4
new                             4
sector 3a                       4
sector 12a                      4
patel nagar                     3
a block sector 43               3
maruti kunj                     3
b block sector 43               3
sector 17a                      3
sector 88b                      3
sector 17b                      3
sector 27                       3
sector 110 a                    3
sector 15                       3
Name: count, dtype: int64

In [25]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [26]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
8,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2.0,2.0,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
994,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4.0,4.0,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1861,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4.0,4.0,2,"Study Room,Servant Room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
3659,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2.0,2.0,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [27]:
df.loc[8,'sector'] = 'sector 37'
df.loc[994,'sector'] = 'sector 92'
df.loc[1861,'sector'] = 'sector 90'
df.loc[3659,'sector'] = 'sector 76'

In [28]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
543,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3.0,2.0,2,Pooja Room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
813,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2.0,2.0,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1273,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2.0,1.0,1,Others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
2869,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2.0,2.0,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3126,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2.0,2.0,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [29]:
df.loc[[543,813,1273,2869,3126],'sector'] = 'sector 110'

In [30]:
df.shape

(3852, 21)

In [31]:
df.duplicated().sum()

np.int64(2)

In [32]:
df.drop_duplicates()

                                          property_name property_type  \
0                           1 BHK Flat in Surat Nagar 1          flat
1                      2 BHK Flat in Sector 103 Gurgaon          flat
2               3 BHK Flat in Dwarka Expressway Gurgaon          flat
3                       4 BHK Flat in Sector 60 Gurgaon          flat
4                       1 BHK Flat in Sector 36 Gurgaon          flat
5                                 4 BHK Flat in Suncity          flat
6                       2 BHK Flat in Sector 89 Gurgaon          flat
7              3 Bedroom House for sale in South City 1         house
8                             2 BHK Flat in New Gurgaon          flat
9                      2 BHK Flat in Sector 102 Gurgaon          flat
10                     3 BHK Flat in Sector 106 Gurgaon          flat
11                      2 BHK Flat in Sector 74 Gurgaon          flat
12              5 Bedroom House for sale in DLF Phase 2         house
13                     3 BHK Flat in Sector 37D Gurgaon          flat
14                     2 BHK Flat in Sector 70A Gurgaon          flat
15    2 Bedroom House for sale in Palam Vihar Extension         house
16        5 Bedroom House for sale in Sector 33 Gurgaon         house
17              4 Bedroom House for sale in Patel Nagar         house
19                        3 BHK Flat in Nirvana Country          flat
20                      2 BHK Flat in Sector 65 Gurgaon          flat
21       12 Bedroom House for sale in Sector 55 Gurgaon         house
22        4 Bedroom House for sale in Sector 72 Gurgaon         house
23                      2 BHK Flat in Sector 61 Gurgaon          flat
24                      3 BHK Flat in Sector 92 Gurgaon          flat
25                      2 BHK Flat in Sector 92 Gurgaon          flat
26                     3 BHK Flat in Sector 102 Gurgaon          flat
27                      2 BHK Flat in Sector 90 Gurgaon          flat
28                     4 BHK Flat in Sector 109 Gurgaon          flat
29                      3 BHK Flat in Sector 92 Gurgaon          flat
30              8 Bedroom House for sale in DLF Phase 3         house
31                     4 BHK Flat in Sector 37D Gurgaon          flat
32       5 Bedroom House for sale in Sector 109 Gurgaon         house
33                      3 BHK Flat in Sector 92 Gurgaon          flat
34                     3 BHK Flat in Sector 113 Gurgaon          flat
35                      4 BHK Flat in Sector 39 Gurgaon          flat
36                      2 BHK Flat in Sector 79 Gurgaon          flat
37                     2 BHK Flat in Sector 102 Gurgaon          flat
38                      3 BHK Flat in Sector 51 Gurgaon          flat
39       18 Bedroom House for sale in Sector 55 Gurgaon         house
40                      3 BHK Flat in Sector 48 Gurgaon          flat
42             2 Bedroom House for sale in Laxman Vihar         house
43                      3 BHK Flat in Sector 74 Gurgaon          flat
44                                  1 BHK Flat in Sohna          flat
45          4 Bedroom House for sale in Nirvana Country         house
46        6 Bedroom House for sale in Sector 38 Gurgaon         house
47         3 Bedroom House for sale in Sector 4 Gurgaon         house
48          3 Bedroom House for sale in Dayanand Colony         house
49                             3 BHK Flat in New Colony          flat
50                     3 BHK Flat in Sector 102 Gurgaon          flat
51                      3 BHK Flat in Sector 83 Gurgaon          flat
52                      3 BHK Flat in Sector 79 Gurgaon          flat
53        4 Bedroom House for sale in Sector 48 Gurgaon         house
54                      2 BHK Flat in Sector 70 Gurgaon          flat
55                      3 BHK Flat in Sector 86 Gurgaon          flat
56             10 Bedroom House for sale in DLF Phase 3         house
57                      3 BHK Flat in Sector 69 Gurgaon          flat
58                     2 BHK Flat in Sector 104 Gurgaon          flat
59                      2 BHK Flat in Sector 47 Gurgaon          flat
60                      3 BHK Flat in Sector 28 Gurgaon          flat
61                     3 BHK Flat in Sector 104 Gurgaon          flat
62     3 Bedroom House for sale in Laxman Vihar Phase 2         house
63                      2 BHK Flat in Sector 61 Gurgaon          flat
64                     3 BHK Flat in Sector 37D Gurgaon          flat
65                      2 BHK Flat in Sector 79 Gurgaon          flat
66                     5 BHK Flat in Sector 110 Gurgaon          flat
67       3 Bedroom House for sale in Sector 103 Gurgaon         house
68                      3 BHK Flat in Sector 90 Gurgaon          flat
69                      4 BHK Flat in Sector 90 Gurgaon          flat
70       5 Bedroom House for sale in Sector 109 Gurgaon         house
71                     2 BHK Flat in Sector 102 Gurgaon          flat
72                           2 BHK Flat in Laxman Vihar          flat
73                     4 BHK Flat in Sector 110 Gurgaon          flat
74                     3 BHK Flat in Sector 106 Gurgaon          flat
75                      2 BHK Flat in Sector 68 Gurgaon          flat
76                      3 BHK Flat in Sector 79 Gurgaon          flat
77                      3 BHK Flat in sector 58 Gurgaon          flat
79                      3 BHK Flat in Sector 67 Gurgaon          flat
80        5 Bedroom House for sale in Sector 81 Gurgaon         house
81                     2 BHK Flat in Sector 108 Gurgaon          flat
82                     3 BHK Flat in Sector 102 Gurgaon          flat
83                      3 BHK Flat in Sector 79 Gurgaon          flat
84                      3 BHK Flat in Sector 92 Gurgaon          flat
85               4 Bedroom House for sale in Sohna Road         house
86                      2 BHK Flat in sector 58 Gurgaon          flat
88                     3 BHK Flat in Sector 103 Gurgaon          flat
89                     2 BHK Flat in Sector 67A Gurgaon          flat
90          5 Bedroom House for sale in Nirvana Country         house
91                      3 BHK Flat in Sector 65 Gurgaon          flat
92      3 Bedroom House for sale in Sushant Lok Phase 1         house
93         4 Bedroom House for sale in Sector 8 Gurgaon         house
94                                  2 BHK Flat in Sohna          flat
95                      2 BHK Flat in Sector 81 Gurgaon          flat
96        5 Bedroom House for sale in Sector 66 Gurgaon         house
97                      3 BHK Flat in Sector 90 Gurgaon          flat
98                      2 BHK Flat in Sector 79 Gurgaon          flat
99        3 Bedroom House for sale in Sector 14 Gurgaon         house
100                     3 BHK Flat in Sector 86 Gurgaon          flat
101                          3 BHK Flat in South City 1          flat
102                    3 BHK Flat in Sector 99A Gurgaon          flat
103                     3 BHK Flat in Sector 68 Gurgaon          flat
104                    4 BHK Flat in Sector 113 Gurgaon          flat
105                     4 BHK Flat in Sector 82 Gurgaon          flat
106         4 Bedroom House for sale in Nirvana Country         house
107                     2 BHK Flat in Sector 89 Gurgaon          flat
108                    2 BHK Flat in Sector 108 Gurgaon          flat
109                     2 BHK Flat in Sector 93 Gurgaon          flat
110                     3 BHK Flat in Sector 70 Gurgaon          flat
111                     2 BHK Flat in Sector 85 Gurgaon          flat
112                     4 BHK Flat in Sector 92 Gurgaon          flat
113                    2 BHK Flat in Sector 70A Gurgaon          flat
114                     3 BHK Flat in Sector 84 Gurgaon          flat
115                     3 BHK Flat in Sector 84 Gurgaon          flat
116                     3 BHK Flat in Sector 66 Gurgaon          flat
117                       3 BHK Flat in Sector-33 Sohna          flat
118                     2 BHK Flat in Sector 86 Gurgaon          flat
119    16 Bedroom House for sale in Sushant Lok Phase 1         house
120                     2 BHK Flat in Sector 89 Gurgaon          flat
121                     4 BHK Flat in Sector 77 Gurgaon          flat
122                    2 BHK Flat in Sector 107 Gurgaon          flat
123      4 Bedroom House for sale in Sector 70A Gurgaon         house
124                                 2 BHK Flat in Sohna          flat
125                     5 BHK Flat in Sector 51 Gurgaon          flat
126                                 3 BHK Flat in Sohna          flat
127          3 Bedroom House for sale in Devilal Colony         house
128                     1 BHK Flat in Sector 95 Gurgaon          flat
129            3 Bedroom House for sale in Laxman Vihar         house
130                     2 BHK Flat in Sector 84 Gurgaon          flat
131                    2 BHK Flat in Sector 88A Gurgaon          flat
132                    1 BHK Flat in Sector 104 Gurgaon          flat
133                    1 BHK Flat in Sector 106 Gurgaon          flat
134                    2 BHK Flat in Sector 107 Gurgaon          flat
135                     4 BHK Flat in Sector 99 Gurgaon          flat
136                     2 BHK Flat in Sector 81 Gurgaon          flat
137                    2 BHK Flat in Sector 67A Gurgaon          flat
138                      2 BHK Flat in Sector 3 Gurgaon          flat
139                    3 BHK Flat in Sector 113 Gurgaon          flat
140                     4 BHK Flat in Sector 81 Gurgaon          flat
141                     3 BHK Flat in Sector 69 Gurgaon          flat
142      4 Bedroom House for sale in Sector 109 Gurgaon         house
143                     3 BHK Flat in Sector 67 Gurgaon          flat
144                     3 BHK Flat in Sector 85 Gurgaon          flat
145                          2 BHK Flat in Laxman Vihar          flat
146                     2 BHK Flat in Sector 81 Gurgaon          flat
147                     2 BHK Flat in Sector 86 Gurgaon          flat
148                     3 BHK Flat in Sector 82 Gurgaon          flat
149                                 2 BHK Flat in Sohna          flat
150                  4 BHK Flat in Sector 1 Imt Manesar          flat
151     5 Bedroom House for sale in Ashok Vihar Phase 2         house
152                     4 BHK Flat in Sector 69 Gurgaon          flat
153                    3 BHK Flat in Sector 112 Gurgaon          flat
154                     4 BHK Flat in Sector 90 Gurgaon          flat
155             3 Bedroom House for sale in Ashok Vihar         house
156                     1 BHK Flat in Sector 49 Gurgaon          flat
157                     3 BHK Flat in Sector 48 Gurgaon          flat
158                     2 BHK Flat in Sector 76 Gurgaon          flat
159       3 Bedroom House for sale in Sector 66 Gurgaon         house
160                    2 BHK Flat in Sector 63A Gurgaon          flat
161                     4 BHK Flat in Sector 54 Gurgaon          flat
162                     4 BHK Flat in Sector 81 Gurgaon          flat
163                     3 BHK Flat in Sector 62 Gurgaon          flat
164                     3 BHK Flat in Sector 81 Gurgaon          flat
165                     4 BHK Flat in Sector 54 Gurgaon          flat
166                    2 BHK Flat in Sector 95A Gurgaon          flat
167                    4 BHK Flat in Sector 110 Gurgaon          flat
168                     3 BHK Flat in Sector 71 Gurgaon          flat
169                     3 BHK Flat in Sector 81 Gurgaon          flat
170                            2 BHK Flat in Sohna Road          flat
172                     4 BHK Flat in Sector 92 Gurgaon          flat
173                     3 BHK Flat in Sector 65 Gurgaon          flat
174                     3 BHK Flat in Sector 84 Gurgaon          flat
175                       3 BHK Flat in Sector-33 Sohna          flat
176                     3 BHK Flat in Sector 89 Gurgaon          flat
177                     3 BHK Flat in Sector 92 Gurgaon          flat
178      5 Bedroom House for sale in Sector 109 Gurgaon         house
179                     3 BHK Flat in Sector 69 Gurgaon          flat
180                                 2 BHK Flat in Sohna          flat
181                     4 BHK Flat in Sector 83 Gurgaon          flat
182      5 Bedroom House for sale in Sector 112 Gurgaon         house
183                     3 BHK Flat in Sector 78 Gurgaon          flat
184      2 Bedroom House for sale in Sector 70A Gurgaon         house
185                     3 BHK Flat in Sector 82 Gurgaon          flat
186             6 Bedroom House for sale in DLF Phase 2         house
187                     4 BHK Flat in Sector 90 Gurgaon          flat
188                     3 BHK Flat in Sector 22 Gurgaon          flat
189                     3 BHK Flat in Sector 86 Gurgaon          flat
190                    4 BHK Flat in Sector 109 Gurgaon          flat
191                     4 BHK Flat in Sector 60 Gurgaon          flat
192                    2 BHK Flat in Sector 82A Gurgaon          flat
193                     3 BHK Flat in Sector 81 Gurgaon          flat
194                    2 BHK Flat in Sector 103 Gurgaon          flat
195       5 Bedroom House for sale in Sector 14 Gurgaon         house
196      1 Bedroom House for sale in Sector 110 Gurgaon         house
197                    3 BHK Flat in Sector 108 Gurgaon          flat
198                     4 BHK Flat in Sector 69 Gurgaon          flat
199                     2 BHK Flat in Sector 81 Gurgaon          flat
200                     4 BHK Flat in Sector 69 Gurgaon          flat
201                     3 BHK Flat in Sector 92 Gurgaon          flat
202                     1 BHK Flat in Sector 47 Gurgaon          flat
203                    2 BHK Flat in Sector 99A Gurgaon          flat
204                    3 BHK Flat in Sector 99A Gurgaon          flat
205                     2 BHK Flat in Sector 86 Gurgaon          flat
207                     2 BHK Flat in Sector 33 Gurgaon          flat
208                       3 BHK Flat in Sector-33 Sohna          flat
209                     3 BHK Flat in Sector 65 Gurgaon          flat
210                    2 BHK Flat in Sector 113 Gurgaon          flat
211                    3 BHK Flat in Sector 37D Gurgaon          flat
212                       2 BHK Flat in Sector-33 Sohna          flat
213                    2 BHK Flat in Sector 99A Gurgaon          flat
214                     4 BHK Flat in Sector 78 Gurgaon          flat
215                     4 BHK Flat in Sector 62 Gurgaon          flat
216                    3 BHK Flat in Sector 109 Gurgaon          flat
217                     3 BHK Flat in Sector 65 Gurgaon          flat
218                10 Bedroom House for sale in Bhondsi         house
219                           3 BHK Flat in Gwal Pahari          flat
222                       4 BHK Flat in Sector-33 Sohna          flat
223                     4 BHK Flat in Sector 92 Gurgaon          flat
224                     2 BHK Flat in Sector 89 Gurgaon          flat
225                     2 BHK Flat in Sector 85 Gurgaon          flat
226                     4 BHK Flat in Sector 82 Gurgaon          flat
227                     3 BHK Flat in Sector 86 Gurgaon          flat
229                           2 BHK Flat in Gwal Pahari          flat
230                     4 BHK Flat in Sector 84 Gurgaon          flat
231                     2 BHK Flat in Sector 90 Gurgaon          flat
232                     3 BHK Flat in Sector 9A Gurgaon          flat
233       5 Bedroom House for sale in Sector 54 Gurgaon         house
234                     3 BHK Flat in Sector 54 Gurgaon          flat
235                     3 BHK Flat in Sector 69 Gurgaon          flat
236                     3 BHK Flat in Sector 84 Gurgaon          flat
237             4 Bedroom House for sale in DLF Phase 4         house
238             5 Bedroom House for sale in DLF Phase 1         house
239                     2 BHK Flat in Sector 99 Gurgaon          flat
240         6 Bedroom House for sale in Uppals Southend         house
241                    2 BHK Flat in Sector 63A Gurgaon          flat
242                    2 BHK Flat in Sector 103 Gurgaon          flat
243         5 Bedroom House for sale in Nirvana Country         house
244       3 Bedroom House for sale in Sector 38 Gurgaon         house
245      5 Bedroom House for sale in Sector 109 Gurgaon         house
246                    2 BHK Flat in Sector 107 Gurgaon          flat
247        4 Bedroom House for sale in Sector 7 Gurgaon         house
248                    4 BHK Flat in Sector 102 Gurgaon          flat
249                    2 BHK Flat in Sector 107 Gurgaon          flat
250            10 Bedroom House for sale in Rajiv Nagar         house
251                     2 BHK Flat in Sector 86 Gurgaon          flat
252                     3 BHK Flat in Sector 80 Gurgaon          flat
253                     4 BHK Flat in Sector 92 Gurgaon          flat
254                     3 BHK Flat in Sector 77 Gurgaon          flat
255       9 Bedroom House for sale in Sector 47 Gurgaon         house
256                                 2 BHK Flat in Sohna          flat
257                     3 BHK Flat in Sector 81 Gurgaon          flat
258           3 Bedroom House for sale in Rajendra Park         house
259                       3 BHK Flat in Nirvana Country          flat
260                     3 BHK Flat in Sector 86 Gurgaon          flat
261           5 Bedroom House for sale in Shivaji Nagar         house
262                     2 BHK Flat in Sector 74 Gurgaon          flat
263                     4 BHK Flat in Sector 56 Gurgaon          flat
264                    2 BHK Flat in Sector 102 Gurgaon          flat
265         3 Bedroom House for sale in Nirvana Country         house
266       4 Bedroom House for sale in Sector 48 Gurgaon         house
267                    2 BHK Flat in Sector 103 Gurgaon          flat
268                     4 BHK Flat in Sector 81 Gurgaon          flat
269                     2 BHK Flat in Sector 79 Gurgaon          flat
270                 4 Bedroom House for sale in Suncity         house
271                     2 BHK Flat in Sector 85 Gurgaon          flat
272                     2 BHK Flat in Sector 78 Gurgaon          flat
273                     3 BHK Flat in Sector 48 Gurgaon          flat
274       6 Bedroom House for sale in Sector 55 Gurgaon         house
275       4 Bedroom House for sale in Sector 48 Gurgaon         house
276       5 Bedroom House for sale in Sector 56 Gurgaon         house
277      12 Bedroom House for sale in Sector 40 Gurgaon         house
278                     4 BHK Flat in Sector 92 Gurgaon          flat
279                     4 BHK Flat in Sector 71 Gurgaon          flat
280              2 Bedroom House for sale in New Colony         house
281                     2 BHK Flat in Sector 79 Gurgaon          flat
283        9 Bedroom House for sale in Sector 9 Gurgaon         house
284                    3 BHK Flat in Sector 37D Gurgaon          flat
285                       2 BHK Flat in Sector-33 Sohna          flat
286                     3 BHK Flat in Sector 61 Gurgaon          flat
287                                 2 BHK Flat in Sohna          flat
288             6 Bedroom House for sale in DLF Phase 1         house
289                    3 BHK Flat in Sector 102 Gurgaon          flat
290     7 Bedroom House for sale in Sushant Lok Phase 1         house
291      4 Bedroom House for sale in Sector 109 Gurgaon         house
292                       3 BHK Flat in Sector-33 Sohna          flat
293                     2 BHK Flat in Sector 30 Gurgaon          flat

In [33]:
# features dropping -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [35]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
347,flat,signature global solera,sector 107,0.35,6398.0,547.0,Carpet area: 547 (50.82 sq.m.),2.0,2.0,2,not available,8.0,South,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...","['1 Fan', '1 Light', '1 Modular Kitchen', 'No ...","['Power Back-up', 'Intercom Facility', 'Lift(s..."
3896,flat,experion the heartsong,sector 108,3.00,18392.0,1631.0,Super Built up area 2779(258.18 sq.m.)Built Up...,4.0,5.0,3+,Servant Room,2.0,South-West,1 to 5 Year Old,"['Galleria 108 Mall', 'Dwarka Expressway', 'Ce...","['1 Water Purifier', '8 Fan', '1 Fridge', '1 E...","['Water purifier', 'Security / Fire Alarm', 'F..."
360,flat,conscient elevate,sector 59,3.78,16500.0,2291.0,Carpet area: 2295 (213.21 sq.m.),3.0,3.0,3,not available,3.0,NaN,By 2024,"['Rapid Metro Station Sector 55', 'Paras Trini...",[],"['Power Back-up', 'Intercom Facility', 'Lift(s..."
1206,house,uppal southend,sector 49,3.75,25562.0,1467.0,Built Up area: 163 (136.29 sq.m.),6.0,6.0,3+,Study Room,3.0,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","['12 Fan', '1 Exhaust Fan', '6 Geyser', '24 Li...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."
3105,flat,emaar palm gardens,sector 83,1.40,8139.0,1720.0,Super Built up area 1720(159.79 sq.m.)Carpet a...,3.0,3.0,3,"Servant Room,Study Room,Pooja Room,Store Room",2.0,North-West,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...","['5 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'..."

In [36]:
df.duplicated().sum()

np.int64(130)

In [37]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)